<?php
$all_process=array();
$all_process[]=array("name"=>"fileupload","file"=>"func_process_fileupload.php");
$all_process[]=array("name"=>"filemultiupload","file"=>"func_process_filemultiupload.php");
$all_process[]=array("name"=>"url_catcher","file"=>"func_process_urlcatcher.php");
$all_process[]=array("name"=>"file_delete","file"=>"func_process_file_delete.php");
$all_process[]=array("name"=>"session","file"=>"func_process_session.php");
$all_process[]=array("name"=>"condition","file"=>"func_process_condition.php");
$all_process[]=array("name"=>"change_page","file"=>"func_process_change_page.php");
$all_process[]=array("name"=>"generate_unique_code","file"=>"func_process_generate_unique_code.php");
$all_process[]=array("name"=>"table","file"=>"func_process_table.php");
$all_process[]=array("name"=>"json_to_array","file"=>"func_process_json_to_array.php");
$all_process[]=array("name"=>"encrypt_sha256","file"=>"func_process_encrypt_sha256.php");
$all_process[]=array("name"=>"declare_variable","file"=>"func_process_declare_variable.php");
$all_process[]=array("name"=>"set_variable","file"=>"func_process_set_variable.php");
$all_process[]=array("name"=>"while","file"=>"func_process_while.php");
$all_process[]=array("name"=>"thetime","file"=>"func_process_thetime.php");
$all_process[]=array("name"=>"create_var_js","file"=>"func_process_create_var_js.php");
$all_process[]=array("name"=>"concat_string","file"=>"func_process_concat_string.php");
$all_process[]=array("name"=>"string_href","file"=>"func_process_string_href.php");
$all_process[]=array("name"=>"crafted","file"=>"func_process_crafted.php");
$all_process[]=array("name"=>"catch_incoming_data","file"=>"func_process_catch_incoming_data.php");
$all_process[]=array("name"=>"print_variable","file"=>"func_process_print_variable.php");

 ?>
